### ISSUE TITLE
monitor material based fitting

### ISSUE THREAD

**Issue by robertnurnberg** [official-stockfish/WDL_model#152]
This is not an issue per se, but just a convenient place to regularly check how our material based fitting works.

Below I report on the fits from `./updateWDL.sh --firstrev b59786e750a59d3d7cff2630cf284553f607ed29`  (based on move) and from `python scoreWDL.py updateWDL.json --plot save --pgnName update_material.png --momType "material" --momTarget 62 --moveMin 8 --moveMax 120 --materialMin 10 --materialMax 78 --modelFitting optimizeProbability` applied to the same json data (based on material).

![update_move](https://github.com/official-stockfish/WDL_model/assets/28635489/5daee22a-7f43-4665-ac8a-58d73ad3f1c7)

![update_material](https://github.com/official-stockfish/WDL_model/assets/28635489/42294cfe-b42d-4811-bd80-a5dfc54f8af2)

json data: [updateWDL.json.gz](https://github.com/official-stockfish/WDL_model/files/13701177/updateWDL.json.gz)

**Comment by robertnurnberg** [comment]
For completeness, I also attach a plot of output of the command `python scoreWDL.py updateWDL.json --plot save --pgnName update_moveshort.png --moveMin 10 --moveMax 78 --modelFitting optimizeProbability`, to compare the relative "smoothness" of the `a` and `b` curves. (The data range here is `[10,78]`, the same as in the material plot.)

![update_moveshort](https://github.com/official-stockfish/WDL_model/assets/28635489/71eb6939-0d04-41c9-ac0c-7f35f8ad0c08)

**Comment by Disservin** [comment]
maybe we want to move this into the wiki?

**Comment by robertnurnberg** [comment]
Let's wait for vondele to return. :)

My plan was to regularly post those plots here, and see if by some miracle the graphs become more smooth in future...

**Comment by vondele** [comment]
This is actually remarkably smooth compared to what we had in SF11 times (classical eval).

I don't mind this as an issue, but one could also put this in the readme as an example for this option.

**Comment by robertnurnberg** [comment]
*If* we are happy with the model in general, and the smoothness in particular, we may want to adopt the material based WDL model for the dynamic normalisation. It would avoid certain problems of the move based one: such as users being confused that the cp eval depends on the move counter when they use SF for analysis of a single position...

**Comment by robertnurnberg** [comment]
Below the graphical outputs corresponding to https://github.com/official-stockfish/Stockfish/pull/5002
for `./updateWDL.sh --firstrev b59786e750a59d3d7cff2630cf284553f607ed29`  (based on move) and from `python scoreWDL.py updateWDL.json --plot save --pgnName update_material.png --momType "material" --momTarget 62 --moveMin 8 --moveMax 120 --materialMin 10 --materialMax 78 --modelFitting optimizeProbability` applied to the same json data (based on material).

![updateWDL](https://github.com/official-stockfish/WDL_model/assets/28635489/ec2e87a3-5cf5-494a-90ae-77b1cf0507bd)

![update_material](https://github.com/official-stockfish/WDL_model/assets/28635489/1043b890-8d45-4dc5-8240-29ef1a8916ab)

**Comment by robertnurnberg** [comment]
Below the graphical outputs corresponding to https://github.com/official-stockfish/Stockfish/pull/5070 for `./updateWDL.sh --firstrev 6deb88728fb141e853243c2873ad0cda4dd19320`  (based on move) and from `python scoreWDL.py updateWDL.json --plot save --pgnName update_material.png --momType "material" --momTarget 62 --moveMin 8 --moveMax 120 --materialMin 10 --materialMax 78 --modelFitting optimizeProbability` applied to the same json data (based on material).

![updateWDL](https://github.com/official-stockfish/WDL_model/assets/28635489/0c707bf2-e018-4b51-bd49-8addaf148f63)

![update_material](https://github.com/official-stockfish/WDL_model/assets/28635489/9528f8f8-1bc1-427d-a1db-a91ad38258ea)

**Comment by robertnurnberg** [comment]
Here is the latest fitting based on material count:

![update_material](https://github.com/official-stockfish/WDL_model/assets/28635489/03638904-8766-4c08-81fc-fe211436698a)

I have prepared the branch https://github.com/robertnurnberg/Stockfish/tree/wdl-material-dynamic to potentially merge into SF. Do we think it is time to do this now? @vondele

**Comment by vondele** [comment]
I think this is ready for integration in SF.

**Comment by robertnurnberg** [comment]
> I think this is ready for integration in SF.

Agreed. Since the anchor now only plays the role of fixing the no-longer-needed constant `NormalizeToPawnValue` (via the sum of the coefficients of the polynomial `p_a`), I will choose it to be the average material count of my LTC games at move 32. In this way there will be some continuity for `NormalizeToPawnValue` from the old move-based WDL model to the new one.

Once I got that, and then fitted the WDL model with this new parameter, I will open a PR to SF.

**Comment by vondele** [comment]
should the issue be closed, since we now use material based WDL?
