### ISSUE TITLE
Food for Thought - Build System

### ISSUE THREAD

**Issue by Disservin** [official-stockfish/WDL_model#155]
What do you think about maybe upgrading the build system to something newer like CMake/Meson?

The Makefile works fine, there's no problem with it, but maybe it's time to try out new tools?
I'd personally would try out Meson, I can write up a patch in the next few days and then we can still decide ? :D

**Comment by robertnurnberg** [comment]
Not sure this repo is the right place to experiment with more modern build systems. The makefile is very simple, and does its job.
