### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by Disservin** [official-stockfish/WDL_model#159]
compiling with `-fsanitize=thread` shows a data race

**Comment by robertnurnberg** [comment]
Is this on master? And also after your chess lib update?

**Comment by Disservin** [comment]
Yes master, was there since ever. Threadsan is telling me something about regexes but i dont see anything wrong with them atm.

**Comment by Disservin** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77704
