### ISSUE TITLE
downloads fail without error message

### ISSUE THREAD

**Issue by robertnurnberg** [official-stockfish/WDL_model#32]
On a fresh clone, I get as output for `python download_fishtest_pgns.py --path pgns --subdirs --page 2`

```
Found 0 fully downloaded tests in pgns/ already.
Downloading pgns to pgns/23-08-30/64efc1bdb0db1f4c8581ee29/ ...
  Fetching 453 missing pgn files ...
Downloading pgns to pgns/23-08-31/64f0565fb0db1f4c8581ffc5/ ...
```

Then killing the process and checking the directory `pgns/23-08-30/64efc1bdb0db1f4c8581ee29` gives an empty directory, whereas the second directory starts to get filled.

Will try to investigate tomorrow.

**Comment by robertnurnberg** [comment]
Ok, so the reason is that the pgn no longer exists: https://tests.stockfishchess.org/api/pgn/64efc1bdb0db1f4c8581ee29-0.pgn.

While http://tests.stockfishchess.org/api/pgn/64f0565fb0db1f4c8581ffc5-0.pgn works.

Will add some error output in the script and then close the issue.

PS: For how long are pgn's stored on fishtest?

**Comment by vondele** [comment]
first, I believe not every task will have a pgn stored, so it will somehow need to deal with that. 

The pgns are not stored for a very long time, LTC runs are stored for longer. https://github.com/official-stockfish/fishtest/blob/master/server/utils/purge_pgn.py
