### ISSUE TITLE
Adopt bulk download in due time

### ISSUE THREAD

**Issue by vondele** [official-stockfish/WDL_model#54]
Once this is in fishtest, we should adopt the bulk download https://github.com/official-stockfish/fishtest/pull/1818

**Comment by ppigazzini** [comment]
Bulk download in fishtest with https://github.com/official-stockfish/fishtest/pull/1823

**Comment by robertnurnberg** [comment]
My understanding is that the per-file download will continue to work (indefinitely?). 

As an intermediate step we could let users of our download script choose between bulk download and per-file download? (Some users may have unstable connections, and downloading large files may often fail, who knows.)

I will be travelling today and likely be busy over the w/e. So the earliest I could look at the new bulk download will be Sun or Mon evening.

PS: A metadata download via an API would also be nice to have, will post something on discord.

**Comment by robertnurnberg** [comment]
Apparently the metadata API already exists, see e.g. https://tests.stockfishchess.org/api/get_run/651eb28b1a7eb9c90315ae2e

**Comment by vondele** [comment]
I would suggest that once we are capable of doing the bulk download we start using it, and drop per file downloads. It will significantly reduce the load on the server and speedup the process of downloading things.

There is another thing, the bulk download will actually give us the .gz pgns, which would save space and if our analysis tool would read .gz files and unzip 'in memory' it would speedup analysis, at least for me (analysis is limited by the HDD BW).

I'm not sure there is an easy way to deal with .gz from within the .cpp analysis program we have, but I guess there is a library out there that could help.

For now, no urgency, the per file download is still working.

**Comment by ppigazzini** [comment]
The bulk download is the more indicated tool to mass download the pgns, however the single pgn download has now an improved implementation:
- the server skips the decompression step, the load is most on MongoDB
- the downloaded file is gzipped and not plain text as before (1/4 of the size)
It's possible to add an api endpoint to get the list of the runs with documents in the pgns collection

**Comment by robertnurnberg** [comment]
Was resolved in https://github.com/official-stockfish/WDL_model/pull/68
